name: GitHub Actions when PR is opened
run-name: ${{ github.actor }} running this ğŸš€

on:
  pull_request:
    branches:
      - main

jobs:
  running_tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running tests"
    name: test-runner
